/*
 * IMT-project
 */

module.exports = {
    item1: 'node app\\testcase\\play-pause.js',
    item2: 'node app\\testcase\\play-pause.js',
    item3: 'node app\\testcase\\edittimeincontrol.js',
    item4: 'node app\\testcase\\edittimeincontrol.js',
    item5: 'node app\\testcase\\edittimeoutcontrol.js',
    item6: 'node app\\testcase\\qixidu.js',
    item7: 'node app\\testcase\\qixidulogin.js',
    item8: 'node app\\testcase\\qixidulogin.js',
    item9: 'node app\\testcase\\speed.js',
    item10: 'node app\\testcase\\speed.js',
    item11: 'node app\\testcase\\volume.js',
    item12: 'node app\\testcase\\novolume.js',
    item13: 'node app\\testcase\\volume.js',
    item14: 'node app\\testcase\\jingxiang.js',
    item15: 'node app\\testcase\\xinao.js',
    item16: 'node app\\testcase\\zidongbofang.js',
    item17: 'node app\\testcase\\huazhonghua.js',
    item18: 'node app\\testcase\\kuanping.js',
    item19: 'node app\\testcase\\wangyequanping.js',
    item20: 'node app\\testcase\\quanping.js',
    item21: 'node app\\testcase\\secaitiaozheng.js',
    item22: 'node app\\testcase\\secaitiaozheng.js',
    item23: 'node app\\testcase\\yinxiaotiaojie.js',
    item24: 'node app\\testcase\\kuaijiejianshuoming.js',
    item25: 'node app\\testcase\\shipinxinxitongji.js',
    item26: 'node app\\testcase\\moresettingsplaytype.js',
    item27: 'node app\\testcase\\moresettingsvideoscale.js',
    item28: 'node app\\testcase\\moresettingsblackside.js',
    item29: 'node app\\testcase\\yinxiaoandbeisu.js',
    item30: 'node app\\testcase\\speedandhuazhonghua.js',
    item31: 'node app\\testcase\\moresettingsplayerchoose.js',
    item32: 'node app\\testcase\\moresettingsdark.js',
    item33: 'node app\\testcase\\yinxiaochongzhi.js',
    item34: 'node app\\testcase\\secaitiaozheng.js',
    item35: 'node app\\testcase\\secaichongzhi.js',
    item36: 'node app\\testcase\\guanbidanmu.js',
    item37: 'node app\\testcase\\danmushezhi.js',
    item38: 'node app\\testcase\\danmushezhibutoumingdu.js',
    item39: 'node app\\testcase\\danmushezhidanmusudu.js',
    item40: 'node app\\testcase\\danmushezhigengduodanmudaxiao.js',
    item41: 'node app\\testcase\\danmushezhigengduodanmusudu.js',
    item42: 'node app\\testcase\\danmushezhigengduomiaobianshezhi.js',
    item43: 'node app\\testcase\\danmushezhiguanbizhinengyun.js',
    item44: 'node app\\testcase\\danmushezhihuifumorenshezhi.js',
    item45: 'node app\\testcase\\danmushezhixianshiquyu.js',
    item46: 'node app\\testcase\\danmushezhizhinengyunpingbi.js',
    item47: 'node app\\testcase\\danmushezhizitidaxiao.js',
    item48: 'node app\\testcase\\yinxiaotiaojiexuanze.js',
}