/*
 * IMT-project
 */

module.exports = {
    item1: 'node app\\edgecases\\play-pause.js',
    item2: 'node app\\edgecases\\play-pause.js',
    item3: 'node app\\edgecases\\edittimeincontrol.js',
    item4: 'node app\\edgecases\\edittimeincontrol.js',
    item5: 'node app\\edgecases\\edittimeoutcontrol.js',
    item6: 'node app\\edgecases\\qixidu.js',
    item7: 'node app\\edgecases\\qixidulogin.js',
    item8: 'node app\\edgecases\\qixidulogin.js',
    item9: 'node app\\edgecases\\speed.js',
    item10: 'node app\\edgecases\\speed.js',
    item11: 'node app\\edgecases\\volume.js',
    item12: 'node app\\edgecases\\novolume.js',
    item13: 'node app\\edgecases\\volume.js',
    item14: 'node app\\edgecases\\jingxiang.js',
    item15: 'node app\\edgecases\\xinao.js',
    item16: 'node app\\edgecases\\zidongbofang.js',
    item17: 'node app\\edgecases\\huazhonghua.js',
    item18: 'node app\\edgecases\\kuanping.js',
    item19: 'node app\\edgecases\\wangyequanping.js',
    item20: 'node app\\edgecases\\quanping.js',
    item21: 'node app\\edgecases\\secaitiaozheng.js',
    item22: 'node app\\edgecases\\secaitiaozheng.js',
    item23: 'node app\\edgecases\\yinxiaotiaojie.js',
    item24: 'node app\\edgecases\\kuaijiejianshuoming.js',
    item25: 'node app\\edgecases\\shipinxinxitongji.js',
    item26: 'node app\\edgecases\\moresettingsplaytype.js',
    item27: 'node app\\edgecases\\moresettingsvideoscale.js',
    item28: 'node app\\edgecases\\moresettingsblackside.js',
    item29: 'node app\\edgecases\\yinxiaoandbeisu.js',
    item30: 'node app\\edgecases\\speedandhuazhonghua.js',
    item31: 'node app\\edgecases\\moresettingsplayerchoose.js',
    item32: 'node app\\edgecases\\moresettingsdark.js',
    item33: 'node app\\edgecases\\yinxiaochongzhi.js',
    item34: 'node app\\edgecases\\secaitiaozheng.js',
    item35: 'node app\\edgecases\\secaichongzhi.js',
    item36: 'node app\\edgecases\\guanbidanmu.js',
    item37: 'node app\\edgecases\\danmushezhi.js',
    item38: 'node app\\edgecases\\danmushezhibutoumingdu.js',
    item39: 'node app\\edgecases\\danmushezhidanmusudu.js',
    item40: 'node app\\edgecases\\danmushezhigengduodanmudaxiao.js',
    item41: 'node app\\edgecases\\danmushezhigengduodanmusudu.js',
    item42: 'node app\\edgecases\\danmushezhigengduomiaobianshezhi.js',
    item43: 'node app\\edgecases\\danmushezhiguanbizhinengyun.js',
    item44: 'node app\\edgecases\\danmushezhihuifumorenshezhi.js',
    item45: 'node app\\edgecases\\danmushezhixianshiquyu.js',
    item46: 'node app\\edgecases\\danmushezhizhinengyunpingbi.js',
    item47: 'node app\\edgecases\\danmushezhizitidaxiao.js',
    item48: 'node app\\edgecases\\yinxiaotiaojiexuanze.js',
}