/*
 * IMT-project
 */

module.exports = {
    item1: 'node app\\firefoxcases\\play-pause.js',
    item2: 'node app\\firefoxcases\\play-pause.js',
    item3: 'node app\\firefoxcases\\edittimeincontrol.js',
    item4: 'node app\\firefoxcases\\edittimeincontrol.js',
    item5: 'node app\\firefoxcases\\edittimeoutcontrol.js',
    item6: 'node app\\firefoxcases\\qixidu.js',
    item7: 'node app\\firefoxcases\\qixidulogin.js',
    item8: 'node app\\firefoxcases\\qixidulogin.js',
    item9: 'node app\\firefoxcases\\speed.js',
    item10: 'node app\\firefoxcases\\speed.js',
    item11: 'node app\\firefoxcases\\volume.js',
    item12: 'node app\\firefoxcases\\novolume.js',
    item13: 'node app\\firefoxcases\\volume.js',
    item14: 'node app\\firefoxcases\\jingxiang.js',
    item15: 'node app\\firefoxcases\\xinao.js',
    item16: 'node app\\firefoxcases\\zidongbofang.js',
    item17: 'node app\\firefoxcases\\huazhonghua.js',
    item18: 'node app\\firefoxcases\\kuanping.js',
    item19: 'node app\\firefoxcases\\wangyequanping.js',
    item20: 'node app\\firefoxcases\\quanping.js',
    item21: 'node app\\firefoxcases\\secaitiaozheng.js',
    item22: 'node app\\firefoxcases\\secaitiaozheng.js',
    item23: 'node app\\firefoxcases\\yinxiaotiaojie.js',
    item24: 'node app\\firefoxcases\\kuaijiejianshuoming.js',
    item25: 'node app\\firefoxcases\\shipinxinxitongji.js',
    item26: 'node app\\firefoxcases\\moresettingsplaytype.js',
    item27: 'node app\\firefoxcases\\moresettingsvideoscale.js',
    item28: 'node app\\firefoxcases\\moresettingsblackside.js',
    item29: 'node app\\firefoxcases\\yinxiaoandbeisu.js',
    item30: 'node app\\firefoxcases\\speedandhuazhonghua.js',
    item31: 'node app\\firefoxcases\\moresettingsplayerchoose.js',
    item32: 'node app\\firefoxcases\\moresettingsdark.js',
    item33: 'node app\\firefoxcases\\yinxiaochongzhi.js',
    item34: 'node app\\firefoxcases\\secaitiaozheng.js',
    item35: 'node app\\firefoxcases\\secaichongzhi.js',
    item36: 'node app\\firefoxcases\\guanbidanmu.js',
    item37: 'node app\\firefoxcases\\danmushezhi.js',
    item38: 'node app\\firefoxcases\\danmushezhibutoumingdu.js',
    item39: 'node app\\firefoxcases\\danmushezhidanmusudu.js',
    item40: 'node app\\firefoxcases\\danmushezhigengduodanmudaxiao.js',
    item41: 'node app\\firefoxcases\\danmushezhigengduodanmusudu.js',
    item42: 'node app\\firefoxcases\\danmushezhigengduomiaobianshezhi.js',
    item43: 'node app\\firefoxcases\\danmushezhiguanbizhinengyun.js',
    item44: 'node app\\firefoxcases\\danmushezhihuifumorenshezhi.js',
    item45: 'node app\\firefoxcases\\danmushezhixianshiquyu.js',
    item46: 'node app\\firefoxcases\\danmushezhizhinengyunpingbi.js',
    item47: 'node app\\firefoxcases\\danmushezhizitidaxiao.js',
    item48: 'node app\\firefoxcases\\yinxiaotiaojiexuanze.js',
}