/*
 * IMT-project
 */

module.exports = {
    item1: 'node app\\iecases\\play-pause.js',
    item2: 'node app\\iecases\\play-pause.js',
    item3: 'node app\\iecases\\edittimeincontrol.js',
    item4: 'node app\\iecases\\edittimeincontrol.js',
    item5: 'node app\\iecases\\edittimeoutcontrol.js',
    item6: 'node app\\iecases\\qixidu.js',
    item7: 'node app\\iecases\\qixidulogin.js',
    item8: 'node app\\iecases\\qixidulogin.js',
    item9: 'node app\\iecases\\speed.js',
    item10: 'node app\\iecases\\speed.js',
    item11: 'node app\\iecases\\volume.js',
    item12: 'node app\\iecases\\novolume.js',
    item13: 'node app\\iecases\\volume.js',
    item14: 'node app\\iecases\\jingxiang.js',
    item15: 'node app\\iecases\\xinao.js',
    item16: 'node app\\iecases\\zidongbofang.js',
    item17: 'node app\\iecases\\huazhonghua.js',
    item18: 'node app\\iecases\\kuanping.js',
    item19: 'node app\\iecases\\wangyequanping.js',
    item20: 'node app\\iecases\\quanping.js',
    item21: 'node app\\iecases\\secaitiaozheng.js',
    item22: 'node app\\iecases\\secaitiaozheng.js',
    item23: 'node app\\iecases\\yinxiaotiaojie.js',
    item24: 'node app\\iecases\\kuaijiejianshuoming.js',
    item25: 'node app\\iecases\\shipinxinxitongji.js',
    item26: 'node app\\iecases\\moresettingsplaytype.js',
    item27: 'node app\\iecases\\moresettingsvideoscale.js',
    item28: 'node app\\iecases\\moresettingsblackside.js',
    item29: 'node app\\iecases\\yinxiaoandbeisu.js',
    item30: 'node app\\iecases\\speedandhuazhonghua.js',
    item31: 'node app\\iecases\\moresettingsplayerchoose.js',
    item32: 'node app\\iecases\\moresettingsdark.js',
    item33: 'node app\\iecases\\yinxiaochongzhi.js',
    item34: 'node app\\iecases\\secaitiaozheng.js',
    item35: 'node app\\iecases\\secaichongzhi.js',
    item36: 'node app\\iecases\\guanbidanmu.js',
    item37: 'node app\\iecases\\danmushezhi.js',
    item38: 'node app\\iecases\\danmushezhibutoumingdu.js',
    item39: 'node app\\iecases\\danmushezhidanmusudu.js',
    item40: 'node app\\iecases\\danmushezhigengduodanmudaxiao.js',
    item41: 'node app\\iecases\\danmushezhigengduodanmusudu.js',
    item42: 'node app\\iecases\\danmushezhigengduomiaobianshezhi.js',
    item43: 'node app\\iecases\\danmushezhiguanbizhinengyun.js',
    item44: 'node app\\iecases\\danmushezhihuifumorenshezhi.js',
    item45: 'node app\\iecases\\danmushezhixianshiquyu.js',
    item46: 'node app\\iecases\\danmushezhizhinengyunpingbi.js',
    item47: 'node app\\iecases\\danmushezhizitidaxiao.js',
    item48: 'node app\\iecases\\yinxiaotiaojiexuanze.js',
}